const actions = {
  UPDATE_PAGES: 'UPDATE_PAGES',
  UPDATE_ACTIVE: 'UPDATE_ACTIVE',
  UPDATE_INFO: 'UPDATE_INFO',
  UPDATE_LEAKS: 'UPDATE_LEAKS',
  UPDATE_PAGE_LEAKS: 'UPDATE_PAGE_LEAKS',
  UPDATE_PAGE_SCRIPTS: 'UPDATE_PAGE_SCRIPTS'
}

export default actions